import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE_URL = 'https://shivekkhurana.com';
const OUTPUT_PATH = 'public/llms.txt';

type Post = {
  title: string;
  subTitle?: string;
  slug: string;
  publishedOn?: string;
  tags?: string[];
};

type Project = {
  title: string;
  companyName: string;
  description: string;
  slug: string;
  startDay: string;
  endDay?: string;
};

type Video = {
  title: string;
  url: string;
  publishedOn?: string;
};

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');

async function readGeneratedJson<T>(path: string): Promise<T[]> {
  const contents = await readFile(join(rootDir, path), 'utf8');
  return JSON.parse(contents) as T[];
}

function byNewestDate<T>(getDate: (item: T) => string | undefined) {
  return (a: T, b: T) => {
    const aTime = new Date(getDate(a) ?? 0).getTime();
    const bTime = new Date(getDate(b) ?? 0).getTime();
    return bTime - aTime;
  };
}

function cleanText(value: string | undefined): string {
  return (value ?? '').replace(/\s+/g, ' ').trim();
}

function cleanSentence(value: string | undefined): string {
  return cleanText(value).replace(/[.?!]+$/, '');
}

function markdownListItem(
  title: string,
  url: string,
  description?: string
): string {
  const summary = cleanText(description);
  return summary ? `- [${title}](${url}): ${summary}` : `- [${title}](${url})`;
}

function formatPost(post: Post): string {
  const date = post.publishedOn ? post.publishedOn.slice(0, 10) : undefined;
  const tags = post.tags?.length ? `Tags: ${post.tags.join(', ')}` : undefined;
  const description = [date, cleanSentence(post.subTitle) || undefined, tags]
    .filter(Boolean)
    .join('. ');

  return markdownListItem(
    post.title,
    `${SITE_URL}/blog/${post.slug}.md`,
    description ? `${description}.` : undefined
  );
}

function formatProject(project: Project): string {
  const dates = [
    project.startDay.slice(0, 10),
    project.endDay?.slice(0, 10) ?? 'present',
  ].join(' to ');

  return markdownListItem(
    `${project.title} at ${project.companyName}`,
    `${SITE_URL}/projects#${project.slug}`,
    `${dates}. ${cleanSentence(project.description)}.`
  );
}

function formatVideo(video: Video): string {
  const date = video.publishedOn ? `${video.publishedOn.slice(0, 10)}. ` : '';
  return markdownListItem(video.title, video.url, `${date}External video.`);
}

async function generateLlmsTxt(): Promise<string> {
  const [posts, projects, videos] = await Promise.all([
    readGeneratedJson<Post>('.contentlayer/generated/Post/_index.json'),
    readGeneratedJson<Project>('.contentlayer/generated/Project/_index.json'),
    readGeneratedJson<Video>('.contentlayer/generated/Video/_index.json'),
  ]);

  const publishedPosts = posts
    .filter((post) => post.publishedOn)
    .sort(byNewestDate((post) => post.publishedOn));

  const sortedProjects = projects.sort(byNewestDate((project) => project.startDay));

  const publishedVideos = videos
    .filter((video) => video.publishedOn)
    .sort(byNewestDate((video) => video.publishedOn));

  return [
    '# Shivek Khurana',
    '',
    '> I make things. Mostly software, but sometimes clothes, courses, videos, or essays.',
    '',
    'This file indexes the main public content on shivekkhurana.com for language models and other automated readers.',
    '',
    '## Core Pages',
    '',
    markdownListItem(
      'Home',
      SITE_URL,
      'Personal homepage, current work, health snapshots, and recent writing.'
    ),
    markdownListItem(
      'About',
      `${SITE_URL}/about`,
      'Background, photographs, and personal context.'
    ),
    markdownListItem(
      'Hire',
      `${SITE_URL}/hire`,
      'Consulting services around AI agents, full-stack product engineering, automation, and evals.'
    ),
    markdownListItem(
      'Projects',
      `${SITE_URL}/projects`,
      'Chronological project and work history.'
    ),
    markdownListItem(
      'Blog',
      `${SITE_URL}/blog`,
      'Essays and technical writing.'
    ),
    markdownListItem(
      'Videos',
      `${SITE_URL}/videos`,
      'Talks and recorded conversations.'
    ),
    markdownListItem(
      'Workouts',
      `${SITE_URL}/workouts`,
      'Public workout dashboard generated from state-of-being data.'
    ),
    markdownListItem(
      'Sleep',
      `${SITE_URL}/sleep`,
      'Sleep dashboard generated from state-of-being data.'
    ),
    markdownListItem(
      'RSS Feed',
      `${SITE_URL}/rss.xml`,
      'Recent blog posts in RSS format.'
    ),
    markdownListItem(
      'Sitemap',
      `${SITE_URL}/sitemap-index.xml`,
      'Machine-readable sitemap generated by Astro.'
    ),
    '',
    '## Blog Posts',
    '',
    ...publishedPosts.map(formatPost),
    '',
    '## Projects',
    '',
    ...sortedProjects.map(formatProject),
    '',
    '## Videos',
    '',
    ...publishedVideos.map(formatVideo),
    '',
  ].join('\n');
}

const llmsTxt = await generateLlmsTxt();
await mkdir(join(rootDir, dirname(OUTPUT_PATH)), { recursive: true });
await writeFile(join(rootDir, OUTPUT_PATH), llmsTxt, 'utf8');

console.log(`Wrote ${OUTPUT_PATH}`);
